
spring:
  application:
    name: fnfo-matchmaking-service
  redis:
    host: localhost
    port: 6379
    timeout: 2000ms
    jedis:
      pool:
        max-active: 10
        max-idle: 5
        min-idle: 2

server:
  port: 8080
  servlet:
    context-path: /

logging:
  level:
    com.fnfo.matchmaking: DEBUG
    org.springframework.data.redis: INFO